<?php

namespace Database\Seeders;

use App\Models\Medicine;
use App\Models\Category;
use Illuminate\Database\Seeder;

class MedicineSeeder extends Seeder
{
    public function run(): void
    {
        $catKeras = Category::where('slug', 'obat-keras')->first()->id ?? 1;
        $catTerbatas = Category::where('slug', 'obat-bebas-terbatas')->first()->id ?? 2;
        $catBebas = Category::where('slug', 'obat-bebas')->first()->id ?? 3;
        $catJamu = Category::where('slug', 'obat-jamu')->first()->id ?? 4;
        $catFitofarmaka = Category::where('slug', 'obat-fitofarmaka')->first()->id ?? 5;

        $medicines = [
            [
                'category_id'    => $catKeras,
                'name'           => 'Amlodipine 10mg Hexpharm',
                'sku_code'       => 'MED-AMLO-010',
                'bpom_number'    => 'GKL0708514010B1',
                'type'           => 'Keras',
                'unit'           => 'Biji',
                'price'          => 1200,
                'purchase_price' => 850,
                'stock'          => 80,
                'min_stock'      => 30,
                'expiry_date'    => '2027-04-20',
                'description'    => 'Obat antihipertensi golongan calcium channel blocker untuk menurunkan tekanan darah.',
            ],
            [
                'category_id'    => $catKeras,
                'name'           => 'Amoxicillin 500mg Bernofarm',
                'sku_code'       => 'MED-AMOX-500',
                'bpom_number'    => 'GKL9802325304A1',
                'type'           => 'Keras',
                'unit'           => 'Biji',
                'price'          => 1100,
                'purchase_price' => 780,
                'stock'          => 64,
                'min_stock'      => 20,
                'expiry_date'    => '2027-09-10',
                'description'    => 'Antibiotik berspektrum luas untuk infeksi bakteri saluran pernapasan, kemih, dan kulit.',
            ],
            [
                'category_id'    => $catKeras,
                'name'           => 'Metformin HCl 500mg Dexa',
                'sku_code'       => 'MED-METF-500',
                'bpom_number'    => 'GKL0305033710A1',
                'type'           => 'Keras',
                'unit'           => 'Biji',
                'price'          => 800,
                'purchase_price' => 550,
                'stock'          => 75,
                'min_stock'      => 15,
                'expiry_date'    => '2027-01-30',
                'description'    => 'Obat antidiabetes oral lini pertama untuk penderita Diabetes Melitus Tipe 2.',
            ],
            [
                'category_id'    => $catTerbatas,
                'name'           => 'Decolgen Flu & Batuk',
                'sku_code'       => 'MED-DECL-TAB',
                'bpom_number'    => 'DTL1404522410A1',
                'type'           => 'Bebas Terbatas',
                'unit'           => 'Biji',
                'price'          => 1500,
                'purchase_price' => 1100,
                'stock'          => 48,
                'min_stock'      => 10,
                'expiry_date'    => '2026-12-31',
                'description'    => 'Meredakan gejala flu seperti bersin, hidung tersumbat, dan sakit kepala.',
            ],
            [
                'category_id'    => $catTerbatas,
                'name'           => 'Cetirizine 10mg Tablet',
                'sku_code'       => 'MED-CETI-010',
                'bpom_number'    => 'GTL0402337110A1',
                'type'           => 'Bebas Terbatas',
                'unit'           => 'Biji',
                'price'          => 1000,
                'purchase_price' => 600,
                'stock'          => 50,
                'min_stock'      => 15,
                'expiry_date'    => '2026-10-30',
                'description'    => 'Antihistamin generasi kedua untuk meredakan rinitis alergi dan gatal-gatal biduran.',
            ],
            [
                'category_id'    => $catTerbatas,
                'name'           => 'Betadine Antiseptic Solution 30ml',
                'sku_code'       => 'MED-BETA-030',
                'bpom_number'    => 'PKD20501710045',
                'type'           => 'Bebas Terbatas',
                'unit'           => 'Flask',
                'price'          => 27000,
                'purchase_price' => 21000,
                'stock'          => 42,
                'min_stock'      => 10,
                'expiry_date'    => '2027-10-15',
                'description'    => 'Cairan antiseptik povidone-iodine 10% kemasan botol flask untuk mencegah infeksi pada luka.',
            ],
            [
                'category_id'    => $catTerbatas,
                'name'           => 'Bioplacenton Gel Luka Bakar 15g',
                'sku_code'       => 'MED-BIOP-GEL',
                'bpom_number'    => 'DTL7211601828A1',
                'type'           => 'Bebas Terbatas',
                'unit'           => 'Tube',
                'price'          => 28000,
                'purchase_price' => 21500,
                'stock'          => 35,
                'min_stock'      => 10,
                'expiry_date'    => '2028-04-15',
                'description'    => 'Gel antiseptik dan penyembuh luka bakar serta luka infeksi dalam sediaan tube aluminium.',
            ],
            [
                'category_id'    => $catBebas,
                'name'           => 'Paracetamol 500mg (Sanmol)',
                'sku_code'       => 'MED-SANM-500',
                'bpom_number'    => 'DBL8822209110A1',
                'type'           => 'Bebas',
                'unit'           => 'Biji',
                'price'          => 500,
                'purchase_price' => 320,
                'stock'          => 120,
                'min_stock'      => 20,
                'expiry_date'    => '2027-11-30',
                'description'    => 'Meredakan rasa sakit kepala, sakit gigi, dan menurunkan demam.',
            ],
            [
                'category_id'    => $catBebas,
                'name'           => 'Promag Tablet Kunyah Dus',
                'sku_code'       => 'MED-PROM-TAB',
                'bpom_number'    => 'DBL9111601963A1',
                'type'           => 'Bebas',
                'unit'           => 'Box',
                'price'          => 28500,
                'purchase_price' => 22500,
                'stock'          => 85,
                'min_stock'      => 15,
                'expiry_date'    => '2027-08-15',
                'description'    => 'Kemasan 1 Box isi 3 strip untuk mengurangi gejala sakit maag karena asam lambung berlebih.',
            ],
            [
                'category_id'    => $catBebas,
                'name'           => 'Salep 2-4 Antijamur Kulit 30g',
                'sku_code'       => 'MED-SLP24-POT',
                'bpom_number'    => 'DBL8304104230A1',
                'type'           => 'Bebas',
                'unit'           => 'Pot',
                'price'          => 12500,
                'purchase_price' => 8500,
                'stock'          => 40,
                'min_stock'      => 10,
                'expiry_date'    => '2027-11-20',
                'description'    => 'Salep kulit asam salisilat dan belerang endap dalam wadah pot plastik untuk gatal dan kudis.',
            ],
            [
                'category_id'    => $catJamu,
                'name'           => 'Tolak Angin Cair Herbal',
                'sku_code'       => 'MED-TLK-ANG',
                'bpom_number'    => 'TR032622221',
                'type'           => 'Jamu',
                'unit'           => 'Sachet',
                'price'          => 4000,
                'purchase_price' => 3000,
                'stock'          => 150,
                'min_stock'      => 30,
                'expiry_date'    => '2028-05-20',
                'description'    => 'Obat jamu herbal tradisional terstandar BPOM TR sachet cair untuk meredakan masuk angin dan mual.',
            ],
            [
                'category_id'    => $catJamu,
                'name'           => 'Antangin JRG Cair Herbal',
                'sku_code'       => 'MED-ANT-JRG',
                'bpom_number'    => 'TR162692241',
                'type'           => 'Jamu',
                'unit'           => 'Sachet',
                'price'          => 3500,
                'purchase_price' => 2600,
                'stock'          => 120,
                'min_stock'      => 25,
                'expiry_date'    => '2028-02-15',
                'description'    => 'Jamu herbal kemasan sachet dengan jahe merah, royal jelly, dan ginseng.',
            ],
            [
                'category_id'    => $catFitofarmaka,
                'name'           => 'Stimuno Forte 50mg Box (Dus 30s)',
                'sku_code'       => 'MED-STM-50M',
                'bpom_number'    => 'FF152300641',
                'type'           => 'Fitofarmaka',
                'unit'           => 'Box',
                'price'          => 88000,
                'purchase_price' => 72000,
                'stock'          => 28,
                'min_stock'      => 10,
                'expiry_date'    => '2027-12-10',
                'description'    => 'Obat Fitofarmaka ekstrak meniran hijau teruji klinis kemasan Box isi 30 kapsul.',
            ],
            [
                'category_id'    => $catFitofarmaka,
                'name'           => 'Tensigard Kapsul Antihipertensi Box',
                'sku_code'       => 'MED-TNS-GRD',
                'bpom_number'    => 'FF142300581',
                'type'           => 'Fitofarmaka',
                'unit'           => 'Box',
                'price'          => 115000,
                'purchase_price' => 95000,
                'stock'          => 22,
                'min_stock'      => 8,
                'expiry_date'    => '2027-08-30',
                'description'    => 'Obat Fitofarmaka ekstrak seledri & kumis kucing teruji klinis Box 30 kapsul.',
            ],
        ];

        foreach ($medicines as $med) {
            Medicine::updateOrCreate(['sku_code' => $med['sku_code']], $med);
        }
    }
}
